"""
Report builder for fsociety.

Generates Markdown reports from debate results and VKG data.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from fsociety.models import ScanSession

logger = logging.getLogger(__name__)


class ReportBuilder:
    """Generates fsociety VAPT reports in Markdown format."""

    def generate(
        self,
        debate_result: dict[str, Any],
        session: ScanSession,
        output_dir: Path,
    ) -> Path:
        """Generate the full report suite."""
        report_dir = output_dir / "report"
        raw_dir = output_dir / "raw"
        report_dir.mkdir(parents=True, exist_ok=True)
        raw_dir.mkdir(parents=True, exist_ok=True)

        # 1. Executive summary
        exec_path = report_dir / "executive_summary.md"
        exec_path.write_text(self._build_executive_summary(debate_result, session), encoding="utf-8")

        # 2. Findings register
        findings_path = report_dir / "findings_register.md"
        findings_path.write_text(self._build_findings_register(debate_result), encoding="utf-8")

        # 3. Remediation roadmap
        remediation_path = report_dir / "remediation_roadmap.md"
        remediation_path.write_text(self._build_remediation_roadmap(debate_result), encoding="utf-8")

        # 4. Raw JSON data
        json_path = raw_dir / "debate_result.json"
        json_path.write_text(json.dumps(debate_result, indent=2, default=str), encoding="utf-8")

        session_path = raw_dir / "session.json"
        session_path.write_text(session.model_dump_json(indent=2), encoding="utf-8")

        logger.info(f"Reports generated in {output_dir}")
        return exec_path

    def _build_executive_summary(self, result: dict, session: ScanSession) -> str:
        """Build the executive summary report."""
        findings = result.get("findings", [])
        posteriors = result.get("posteriors", [])
        vkg = result.get("vkg_summary", {})

        severity_counts = session.severity_counts
        final_posterior = posteriors[-1] if posteriors else 0.0

        # Risk rating
        if severity_counts.get("P0", 0) > 0:
            risk = "🔴 CRITICAL"
        elif severity_counts.get("P1", 0) > 0:
            risk = "🟠 HIGH"
        elif severity_counts.get("P2", 0) > 0:
            risk = "🟡 MEDIUM"
        else:
            risk = "🟢 LOW"

        return f"""# fsociety VAPT Executive Summary

> *"Hello, friend. Here is what we found."*

---

## Target
- **Name:** {session.target.name}
- **Mode:** {session.target.mode}
- **Session:** `{session.session_id}`
- **Date:** {session.started_at or datetime.now()}

## Risk Rating: {risk}

| Severity | Count |
|----------|-------|
| 🔴 P0 Critical | {severity_counts.get('P0', 0)} |
| 🟠 P1 High | {severity_counts.get('P1', 0)} |
| 🟡 P2 Medium | {severity_counts.get('P2', 0)} |
| 🟢 P3 Low | {severity_counts.get('P3', 0)} |
| ℹ️ Info | {severity_counts.get('INFO', 0)} |
| **Total** | **{session.total_findings}** |

## Debate Summary
- **Rounds completed:** {session.debate_rounds}
- **Agents deployed:** {', '.join(session.agents_used)}
- **Final conviction posterior:** {final_posterior:.2%}

## VKG Summary
- Vulnerabilities: {vkg.get('total_vulnerabilities', 0)}
- Exploit chains: {vkg.get('total_exploit_chains', 0)}
- Attack surfaces: {vkg.get('total_attack_surfaces', 0)}
- Mitigations identified: {vkg.get('total_mitigations', 0)}

---

*Generated by fsociety VAPT Intelligence Platform v1.0.0*
"""

    def _build_findings_register(self, result: dict) -> str:
        """Build the detailed findings register."""
        findings = result.get("findings", [])
        lines = [
            "# fsociety Findings Register\n",
            "| # | Severity | Agent | Description | Confidence |",
            "|---|----------|-------|-------------|------------|",
        ]

        for i, f in enumerate(findings, 1):
            sev = f.get("severity", "P2")
            agent = f.get("agent", "unknown")
            text = f.get("text", "No description")[:80]
            conf = f.get("confidence", 0.5)
            lines.append(f"| {i} | {sev} | {agent} | {text} | {conf:.0%} |")

        lines.append(f"\n**Total findings: {len(findings)}**")
        return "\n".join(lines)

    def _build_remediation_roadmap(self, result: dict) -> str:
        """Build the remediation roadmap."""
        findings = result.get("findings", [])

        # Sort by severity (P0 first)
        sev_order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3, "INFO": 4}
        sorted_findings = sorted(findings, key=lambda f: sev_order.get(f.get("severity", "P2"), 3))

        lines = [
            "# fsociety Remediation Roadmap\n",
            "> Prioritized by exploitability × impact\n",
        ]

        for i, f in enumerate(sorted_findings, 1):
            sev = f.get("severity", "P2")
            text = f.get("text", "No description")
            evidence = f.get("evidence", "")

            if sev in ("P0", "CRITICAL"):
                emoji = "🚨"
                effort = "Immediate action required"
            elif sev in ("P1", "HIGH"):
                emoji = "⚠️"
                effort = "Fix within 48 hours"
            elif sev in ("P2", "MEDIUM"):
                emoji = "🔧"
                effort = "Schedule for next sprint"
            else:
                emoji = "📝"
                effort = "Backlog"

            lines.append(f"\n### {emoji} {i}. {text}")
            lines.append(f"- **Severity:** {sev}")
            lines.append(f"- **Timeline:** {effort}")
            if evidence:
                lines.append(f"- **Evidence:** {evidence[:200]}")

        return "\n".join(lines)
